### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Raffa064-zz** [icanerdogan/PoseDetection-MLKit#1]
I don't have a computer, and I'm trying to use mlkit on AIDE (an java compiler for Android)
I think I'm almost done... But this "Camera Kit" library for some reason won't download at all...
Can you send me a download link for this library on a website or upload it somewhere for me to download? apparently that's the only thing I need to run this project.
Thanks in advance!

**Comment by ibrahimcanerdogan** [comment]
I think this library deprecated now. I suggest you use CameraX for this project. 

CameraX : https://developer.android.com/training/camerax
